### PR TITLE
Enables dropdown query types for RPC, CONSTS, etc.

### PR DESCRIPTION
**Pull request by rvalle**
Have a look, it allows for setting a query type.

It would be nice to rename from query state to a more generic query api, but I don't think it is possible or matters that much.

I am going to be testing a bit more, wait for my signal to merge.

Here is the test flow I am using, in case you also want to test:

```
[
    {
        "id": "c19ba37127e3efd6",
        "type": "query state",
        "z": "5a89f275502f4b5a",
        "name": "Test",
        "client": "4d7e2a1e67067c32",
        "qtype": "rpc",
        "method": "system.version()",
        "x": 470,
        "y": 200,
        "wires": [
            [
                "798e65212ce0967b"
            ]
        ]
    },
    {
        "id": "798e65212ce0967b",
        "type": "debug",
        "z": "5a89f275502f4b5a",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 920,
        "y": 280,
        "wires": []
    },
    {
        "id": "4fe74118094b7160",
        "type": "inject",
        "z": "5a89f275502f4b5a",
        "name": "Static Query",
        "props": [
            {
                "p": "now",
                "v": "",
                "vt": "date"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 150,
        "y": 300,
        "wires": [
            [
                "c19ba37127e3efd6",
                "834efa4fe1949635",
                "7a96843867e4dafe"
            ]
        ]
    },
    {
        "id": "834efa4fe1949635",
        "type": "query state",
        "z": "5a89f275502f4b5a",
        "name": "",
        "client": "4d7e2a1e67067c32",
        "qtype": "query",
        "method": "timestamp.now()",
        "x": 520,
        "y": 300,
        "wires": [
            [
                "798e65212ce0967b"
            ]
        ]
    },
    {
        "id": "7a96843867e4dafe",
        "type": "query state",
        "z": "5a89f275502f4b5a",
        "name": "",
        "client": "4d7e2a1e67067c32",
        "qtype": "consts",
        "method": "babe.epochDuration.toNumber()",
        "x": 570,
        "y": 380,
        "wires": [
            [
                "798e65212ce0967b"
            ]
        ]
    },
    {
        "id": "011c9452d9ac8318",
        "type": "query state",
        "z": "5a89f275502f4b5a",
        "name": "",
        "client": "4d7e2a1e67067c32",
        "qtype": "",
        "method": "",
        "x": 470,
        "y": 640,
        "wires": [
            [
                "a5325e49323317c1"
            ]
        ]
    },
    {
        "id": "95e3f437b0858b21",
        "type": "inject",
        "z": "5a89f275502f4b5a",
        "name": "Dynamic Query",
        "props": [
            {
                "p": "qtype",
                "v": "query",
                "vt": "str"
            },
            {
                "p": "method",
                "v": "timestamp.now()",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 180,
        "y": 640,
        "wires": [
            [
                "011c9452d9ac8318"
            ]
        ]
    },
    {
        "id": "a5325e49323317c1",
        "type": "debug",
        "z": "5a89f275502f4b5a",
        "name": "debug 2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 900,
        "y": 640,
        "wires": []
    },
    {
        "id": "4d7e2a1e67067c32",
        "type": "client",
        "name": "Polkadot IO",
        "endpoint": "wss://rpc.polkadot.io/",
        "keytype": "sr25519"
    }
]
```

### CODE REVIEW

**Comment by rvalle** [comment]
mmmm the default query type is not set by default on already deployed flows.

**Comment by rvalle** [comment]
I don't think there is a workaround for this. Looks like we break flows anyway, because they would need to edit existing nodes and set the query type as "query".

I can think on the following options:
- Publish like this, and let people know they need to set the query type.
- Leave query state as it is, and introduce query api, even if they have overlapping functionality.

I am going to check a bit more if there is a better workaround for this.

But looks like NodeRED does not have features to allow rearch of modules (renaming, deprecating, migrating, etc).

**Comment by rvalle** [comment]
I think I have a decent workaround, we check at runtime if query type is missing and we issue a warning while letting the workflow work as before.

**Comment by rvalle** [comment]
@johnuopini This is the final status of this PR:

- New parameter Query Type allows for setting queries form `api.query` (as before), `api.rpc` and `api.consts`
- It is also possible to provide the query type dynamically with `msg.qtype`
- Unfortunately, existing workflows will come with Query Type unset. The node checks the condition at runtime, and informs the user that Query Type needs setting, and that it is defaulting to `query`. This is already the default, but for some reason, Node Red does not set default on old flows. Flows will continue to work, and users will get rid of the warning by setting Query Type correct.y.
- Specific error messages have been added when the message is expected to include the `query type` or the `method` but does not include it.

I think this is good to go, considering what was discussed.

**Review by johnuopini — APPROVED** [review]
Seems good, will roll out 0.12 today

**Pull request merged**
